import type { Metadata } from "next";
import { Inter,Poppins,Asap } from "next/font/google";
import {PrimeReactProvider} from "primereact/api"
import "./globals.css";

const asap = Asap({
  subsets:["latin"],
  weight:["200","500","800","900"],
  variable:"--font-asap"
});
const poppins = Poppins({
  subsets:["latin"],
  weight:["200","500","800","900"],
  variable:"--font-poppins"
})
export const metadata: Metadata = {
  title: "Blac Volta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" imageSrcSet="/assets/images/bgmobile.webp" media="(max-width:640px)" as="image"/>
        <link rel="preload" imageSrcSet="/assets/images/bgtablet.webp" media="((min-width:640.1px) and (max-width:768px)" as="image"/>
        <link rel="preload" imageSrcSet="/assets/images/bgminidesktop.webp" media="(min-width:768.1px) and (max-width:1280px)" as="image"/>
        <link rel="preload" imageSrcSet="/assets/images/bg.webp" media="(min-width:1280.1px)" as="image"/>

      </head>
      <PrimeReactProvider>
        <body className={`${asap.variable} ${poppins.variable}`}>{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
